### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jgm** [pandoc/pandoc-lua-marshal#10]
I think we're close to being able to release pandoc 3.0.
But for that to happen, we need a released version of pandoc-lua-marshal.

**Comment by jgm** [comment]
Unless you think there are further changes we should make to pandoc-types...

**Comment by tarleb** [comment]
It's ready for release and we can do so any time. You are co-maintainer on Hackage, so we don't depend on me for this. It might be good to merge #11 (use released version of pandoc-types) before we release, but it's not strictly necessary, I think.

**Comment by jgm** [comment]
Released!
